version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: businesshoursapidb
    environment:
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
